---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/cnrnoticias/public_html
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp cobertura.html $DEPLOYPATH
    - /bin/cp ensenada.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp rosarito.html $DEPLOYPATH
    - /bin/cp san-diego.html $DEPLOYPATH
    - /bin/cp tecate.html $DEPLOYPATH
    - /bin/cp tecate.html $DEPLOYPATH
    - /bin/cp tijuana.html $DEPLOYPATH
    - /bin/cp mexicali.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R _includes $DEPLOYPATH
    - /bin/cp -R _layouts $DEPLOYPATH  
    - /bin/cp -R _posts $DEPLOYPATH
    - /bin/cp -R _data $DEPLOYPATH 
    