# set JEKYLL_ENV=production | bundle exec jekyll build

title: CNR TV NOTICIAS - CANAL 73 -Unión con Compromiso
email: mariorivera@cnrnoticias.tv
description: >- 
  Canal de televisión del Estado de Baja California. Siempre llevando la noticia en tiempo y forma sin filtros. Comprometidos con la comunidad. 
baseurl: "" 
url: "https://cnrnoticias.tv"
twitter_username: jekyllrb
disqus:
 shortname: cnrnoticias-tv
# Build settings
defaults:
  - scope:
      path: ""
    values:
      image: /img/logos/logo.png
      alt: "CNR 73 ESTATAL"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .github
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
